### ISSUE TITLE
module 'numpy' has no attribute 'atan2'

### ISSUE THREAD

**Issue by LuisNavarroGarcia** [TUDelft-CNS-ATM/bluesky#298] opened 2021-06-30 19:00 UTC
Hi!

I'm not sure if it's a new bug, but when trying a new install from zero, including dependencies, I keep getting this message. I think there are some  functions from 'math' being called from 'numpy' as the function mentioned in the error, in the module numpy, is called 'arctan2'.

Hope it's useful and thank you for the wonderful work put into the sim!

**Comment by jooste** [comment] 2021-06-30 20:27
Thanks! It is indeed a new bug, caused by some edits in the data loading functions. It should be fixed in 2b14443!

**Closed** 2021-07-01 13:41 UTC
