### ISSUE TITLE
CRE command does not initialize the aircraft at the correct lat/lon position

### ISSUE THREAD

**Issue by TiagoMMNunes** [TUDelft-CNS-ATM/bluesky#439] opened 2022-12-07 13:30 UTC
I have been using BlueSky for a ML application. Upon looking further into exactly what was happening with the initialization of the aircraft I noticed that the ownship was being initialized in an incorrect position.

To create the ownship I always use the command:
`stack.stack('CRE KL001 A320 52.0 3.0 180 FL100 265')`

I then use the `creconfs` command to initialize an intruder aircraft with a given relative heading and velocity (initialization values are randomly selected from a range).

The main issue I have ran across is that the `CRE` function appears not to create the aircraft at **exactly** 52degrees lat by 3degrees lon. I have noticed severe deviations. Below you can find an image where, in orange, you can see the ownship positions at time t=0 and , in blue, the same for the intruding aircraft. You can notice that, even though the ownship is **always** created using the exact same command, there are deviations in lat/lon from the requested value (some as high as around 0.25degrees of latitude which would be around 15nm of deviation). 

![image](https://user-images.githubusercontent.com/92160874/206190351-0e70a388-49bf-4cd1-8f2c-2089f8e9d037.png)

The blue dots appear to be symmetric around the 3degree lon line (which is to be expected since the range of possible relative headings of initialization with the CRECONFS function is also symmetrical, `range(25,345,10)` which creates a range from 25 to 335 degrees). 

The lat/lon position is extracted right after the `CRE` command occurs through:
`idx = traf.id.index("KL001")

lat_val = traf.lat[idx]

lon_val = traf.lon[idx]`

**Comment by jooste** [comment] 2022-12-07 13:51
Hi @TiagoMMNunes,

Thanks for checking this with us! I think it's unlikely that you are looking at a problem in the CRE command, since passing floats to it for lat and lon really only performs string-to-float conversion using `float(arg)`. In the following minimal test case I do get the expected numbers:

```python
import bluesky as bs
bs.init(detached=True)

bs.stack.stack('CRE KL001 A320 52.0 3.0 180 FL100 265')
bs.stack.simstack.process()

bs.traf.lat  # prints array([52.])
bs.traf.lon  # prints array([3.])
```
If you try this (e.g., in ipython), do you get the same?

**Comment by TiagoMMNunes** [comment] 2022-12-07 14:32
I am running an older version of bluesky which I dont think supports the detached command. This is what I get:
`
Traceback (most recent call last):
  File "C:/Users/tmmonteironune/Desktop/Coding and scripts/BlueSky DQFD/bluesky-master/Testing_file.py", line 2, in <module>
    bs.init(detached=True)
TypeError: init() got an unexpected keyword argument 'detached'
`
However when I use it in my current code as
`
print(traf.lat)  # prints array([52.])
print(traf.lon)
`

It prints similar values to the ones I said above

**Comment by jooste** [comment] 2022-12-07 14:59
That you are using an older version doesn't make things easier. However, unless it's (way) older than two years I still don't think the problem is with CRE. Neither Traffic.cre() nor the stack argument parsing functions have (relevant) changes that are more recent than 2 years.

I would recommend you update to the current version of BlueSky, and if possible to put your work on github. This should make it easier to help out in finding where the problem is.

**Comment by TiagoMMNunes** [comment] 2022-12-08 10:44
I am currently trying to update to the newest version of bluesky. When using the check.py (after installing all the packages) i get the following error traceback:

```
Checking for numpy               [OK]
Checking for scipy               [OK]
Checking for matplotlib          [OK]
Checking for pyqt                [QT 6.4.0]
Checking for pyopengl            [OK]
OpenGL module version is         [3.1.1a1]
Checking GL capabilities         Traceback (most recent call last):
  File "C:/Users/tmmonteironune/Desktop/Coding and scripts/bluesky-master-updated-version/bluesky-master/check.py", line 73, in <module>
    if not QGLFormat.hasOpenGL():
AttributeError: type object 'QSurfaceFormat' has no attribute 'hasOpenGL'

Process finished with exit code 1
```

I am using Python3.7 with Anaconda

**Comment by jooste** [comment] 2022-12-08 12:02
Have you tried just starting bluesky itself?
check.py has not been updated since moving to Qt6. There are quite a few differences in terms of OpenGL implementation between Qt5 and Qt6, which means that if you are using Qt6, check.py is not reliable.

Note that if you are on windows it may be preferable to use Qt5, since Qt6 is known to cause issues on Windows at the moment.

**Comment by TiagoMMNunes** [comment] 2022-12-08 12:39
I am indeed on windows and so only installed Qt5 as per your reccomendations. When running BlueSky I get this 
```
Traceback (most recent call last):
  File "C:/Users/tmmonteironune/Desktop/Coding and scripts/bluesky-master-updated-version/bluesky-master/BlueSky.py", line 4, in <module>
    from bluesky.__main__ import main
  File "C:\Users\tmmonteironune\Desktop\Coding and scripts\bluesky-master-updated-version\bluesky-master\bluesky\__init__.py", line 2, in <module>
    from bluesky import settings
  File "C:\Users\tmmonteironune\Desktop\Coding and scripts\bluesky-master-updated-version\bluesky-master\bluesky\settings.py", line 4, in <module>
    from bluesky.pathfinder import resource
  File "C:\Users\tmmonteironune\Desktop\Coding and scripts\bluesky-master-updated-version\bluesky-master\bluesky\pathfinder.py", line 105, in <module>
    resource.path = ResourcePath()
  File "C:\Users\tmmonteironune\Desktop\Coding and scripts\bluesky-master-updated-version\bluesky-master\bluesky\pathfinder.py", line 37, in __init__
    super().__init__(*paths)
TypeError: __init__() argument after * must be an iterable, not _GeneratorContextManager

Process finished with exit code 1
```
I assume this is a problem with the settings.cfg file not existing but even when I paste a settings.cfg file into the main bluesky folder it still doesn't work and gives the same error

**Comment by jooste** [comment] 2022-12-08 13:11
Ah, there's indeed an error there. I don't have older python versions on my machine, so can't easily check. Try updating to commit 2718290, should be a fix for this.

**Comment by TiagoMMNunes** [comment] 2022-12-08 13:19
Indeed now with the new version of bluesky, running the minimal test you presented it outputs correctly lat long as
```
[52.]
[3.]
```
So it appears that it was something wrong with the CRE command in the previous version of BlueSky I am using

**Comment by jooste** [comment] 2022-12-08 13:20
ok, so how old was your previous version of bluesky then?

**Comment by TiagoMMNunes** [comment] 2022-12-08 13:22
Around 2 years old.

**Comment by jooste** [comment] 2022-12-08 13:31
Pretty old then :) Does your own code still work as expected with the up-to-date bluesky?

**Comment by TiagoMMNunes** [comment] 2022-12-08 14:25
It appears to still work properly from the testing I've done so far. Mostly what code I had was in plugins so it doesn't clash with the new version

I did just run the same test as the original I had placed here. The resulting output is the same, the lat/lon values for the ownship KL001 are still deviated from [52 lat, 3 lon]. 

![image](https://user-images.githubusercontent.com/92160874/206471234-577501f8-cb27-4a64-b65b-4853939d36d4.png)


It is perhaps due to something that I am doing within the plugin but I can't quite see where. Below is the code from the point where I Reset the previous simulation to the point where I collect the values for lat/lon

```
stack.stack('RESET')
stack.stack('HOLD')

# Determining next scenario's conflicting aircraft states
# Will change this to vector form in the future for added readability
# States
chosen_conflict_angle = rd.randint(0, len(conflict_angles[0]) - 1)
chosen_initial_dcpa = rd.randint(0, len(possible_initial_dcpa) - 1)
chosen_initial_tlos = rd.randint(0, len(possible_initial_tlos) - 1)

# Creating ownship / controlled a/c. Standard implementation initializes it always at the same point
stack.stack('CRE KL001 A320 52.0 3.0 180 FL100 265')
# Generates the command string for the stack command of creating the intruding aircraft
# CRECONFS id, type, targetid, dpsi, cpa, tlos_hor, dH, tlos_ver, spd
intruder_velocity = 285 - 20 * random.randint(0,2 )

stack.stack('ZONER ' + str(5+0.5))
stack.stack('DTLOOK ' + str(350))
intruder_setup = 'CRECONFS KL002 A320 KL001 ' + str(conflict_angles[0][chosen_conflict_angle]) + ' ' + \
                 str(possible_initial_dcpa[chosen_initial_dcpa]) + ' ' + \
                 str(possible_initial_tlos[chosen_initial_tlos]) + ' 0 0 ' + str(intruder_velocity)
stack.stack('OP')
stack.stack('FF')
stack.stack('FF')

# Standard, housekeeping, initialization of the ASAS, LNAV and MVP alongside limitation of Bank angle and adding
# waypoint to ownship. See init function for a more in depth explanation or the BlueSky wiki for in depth
# explanation of the commands themselves and the stack
stack.stack(intruder_setup)
stack.stack('ASAS ON')
stack.stack('BANK KL001 34')
stack.stack('BANK KL002 34')
stack.stack('LNAV KL001')
stack.stack('LNAV KL002')
stack.stack('ADDWPT KL001 50.5 3')

# Giving command to lookahead time of the CR algorithm
stack.stack('DTLOOK ' + str(350))

# Giving command to change safety factor
stack.stack('ZONER ' + str(5+0.5))
stack.stack('SSD ALL')
# Switching off ability to apply resolutions to the intruding aircraft, DQFD handles resolutions through
# commands not conflict resolution class
stack.stack('RESOOFF KL002')
stack.stack('RESOOFF KL001')
# Gives KL001 a waypoint to follow
stack.stack('ADDWPT KL001 50.5 3')
# Turns on visual trails
stack.stack('TRAIL ON')
stack.stack('FF')
if episode == 0:
    lat_storage = []
    lon_storage = []

    lat_own_storage = []
    lon_own_storage = []

else:
    pass
idx_intru = traf.id.index("KL002")
idx = traf.id.index("KL001")
lat_storage.append(traf.lat[idx_intru])
lon_storage.append(traf.lon[idx_intru])

lat_own_storage.append(traf.lat[idx])
lon_own_storage.append(traf.lon[idx])
```

**Comment by jooste** [comment] 2022-12-08 14:36
The first thing I notice is that your stacked commands aren't processed before you store the lats and lons in your lists. You can do this with either `bs.sim.step()`, which also performs one simulation step, or if you don't want that, use `stack.simstack.process()`.

Because of this you are getting old data in your lists, from the previous episode which probably did perform some simulation steps?

**Closed** 2022-12-08 14:48 UTC
