### ISSUE TITLE
ASAS  - MVP - 'PerfBase' object has no attribute 'vsmin'

### ISSUE THREAD

**Issue by andersmh** [TUDelft-CNS-ATM/bluesky#346] opened 2021-12-06 11:58 UTC
Error occurs when MVP is enabled for all of the documented ASAS scenarios. Furthermore, the problems also occurs when using the OpenAP drone performance models, specifically the M600 (the others have not been tested).

![Screenshot 2021-12-06 125847](https://user-images.githubusercontent.com/31239471/144842222-77248f4e-f3bc-41f2-9af2-ca7789c253b7.png)
![Screenshot 2021-12-06 112045](https://user-images.githubusercontent.com/31239471/144841804-f7df2f5e-1cb6-43ef-85ff-544ca8a1bc91.png)

An effort to hard code vsmin (-5) and vsmax (10) have been performed with no luck. When the numbers are hard coded in, and a resolution between two drones are taken into action, the horizontal speed of the two drones goes to 0, as can be seen below.

![Screenshot 2021-12-06 130641](https://user-images.githubusercontent.com/31239471/144843249-28d30e8e-580c-4969-adae-45ac1542d3cc.png)
![Screenshot 2021-12-06 130218](https://user-images.githubusercontent.com/31239471/144843263-f596b513-299d-458a-bd2c-29d6a9c122b2.png)

**Comment by jooste** [comment] 2021-12-06 13:55
Hi, thanks for the suggestion. The envelope limits weren't all available in the base class of performance, this is fixed in 94674dc. You mention that you see the same issue with the OpenAP performance implementation, I assume you mean the particular impractical resolution, and not the exception in your terminal screenshot? Because the perfOAP class does have a vsmin/vsmax member variable.

**Comment by andersmh** [comment] 2021-12-06 14:24
Hi! Thank you for the quick reply!

The OpenAP I am referring too is located at "bluesky/data/performance/OpenAP/rotor/aircraft.json", where I have used the M600 drone as the aircraft of choice, which does include vsmin/vsmax parameters, so your update did actuallyfix the initial issue for the test cases provided in the ASAS folder, and my generated M600 flights! :)

However, the other issue I mentioned still persists. When using the MVP, and an aircraft needs to take action to prevent a collision, they slow down and stop at a 0. A while later, a broadcast error occurs as can be seen below.
![Screenshot 2021-12-06 151439](https://user-images.githubusercontent.com/31239471/144862540-d373e923-9404-4a1e-9f19-07ca1fe795c1.png)
![Screenshot 2021-12-06 151413](https://user-images.githubusercontent.com/31239471/144862553-13f97772-c947-4f38-99b4-9a7abc374a3f.png)

**Comment by jooste** [comment] 2021-12-06 14:28
that is an unexpected error. Are you running the master version of bluesky? and are you running any plugins?

can you give a full scenario file (or the name of an existing one) where you get this problem?

**Comment by andersmh** [comment] 2021-12-06 14:36
Yes, I am running the master version of bluesky without any plugins (fetched the updated version about 30m ago).

I think it might be easier to troubleshoot with one of the existing files, so the problem can also be found when running "bluesky\scenario\ASAS\ASAS-08.scn"

![Screenshot 2021-12-06 153242](https://user-images.githubusercontent.com/31239471/144864813-56b8e1d8-73fa-45ba-af16-041112aee7bd.png)
![Screenshot 2021-12-06 153319](https://user-images.githubusercontent.com/31239471/144864815-4dd1e7cd-1711-4788-870d-9b1c9ff603c5.png)

**Comment by jooste** [comment] 2021-12-06 14:45
I'm not getting a traceback when running that scenario (but looking from your most recent screenshot, neither are you?) The RuntimeWarning is printed because of a division by zero in line 335 of mvp.py (`vrel[2]` is 0).

**Comment by andersmh** [comment] 2021-12-06 15:20
The issue seems to stems from the fact that the two aircrafts have the same velocities when the CR kicks in, so, when creating the relative vector `vrel` the relative speed will be 0, and this is not check before doing the calculations in line 335.

![Screenshot 2021-12-06 161544](https://user-images.githubusercontent.com/31239471/144871563-e1c2f8ed-74e3-49c7-8630-d53928c33d70.png)

**Comment by jooste** [comment] 2021-12-06 15:52
hmm.. it is actually checked, by the `np.where(abs(vrel[2]) > 0.0`! The only other division in line 335 is with `tsolV`, which for me, when I run the ASAS-8 scenario, is not zero.

**Comment by andersmh** [comment] 2021-12-07 10:22
Ah! Makes sense, however, then the error makes even less sense, `tsolV ` is not zero on my end neither...quite weird

**Comment by jooste** [comment] 2021-12-07 10:33
well, it's a warning, not an error. And depending on how numpy optimises, the divisions by zero might still be calculated, but then just not used because of the `np.where` condition. On my version of numpy it seems that the condition is checked before the calculation is made, and therefore the warning doesn't occur. Since you are now using an older version of python it could be that your installation of numpy doesn't perform this optimisation. At any rate, because of the `np.where` selection, this division by zero shouldn't affect the functioning of MVP.

I'm also interested in the ValueError you were getting in one of your previous screenshots. It shows that `cr.vsactive` and `ap.vs` both have size 9, but `cr.vs` only has size 2. If you have a scenario where this happens I would like to test it as well.

**Comment by andersmh** [comment] 2021-12-07 10:47
Okey! That was quite informative, might need to try with a newer version of python, and compare the results.

With regards to the broadcast error, I have attached a .txt file, and a screenshot of the simulation :)

![Screenshot 2021-12-07 113904](https://user-images.githubusercontent.com/31239471/145014653-cbe8aa12-e750-4b93-a668-9ab9c5713531.png)
[scs.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/7667644/scs.txt)

**Comment by jooste** [comment] 2021-12-07 11:38
Odd, even with that scenario I don't get an error. Which version of python and which version of numpy are you using?

**Comment by andersmh** [comment] 2021-12-07 11:49
I am using: 

python: 3.9.9
numpy: 1.20.1

Any recommendations for which versions I should be using?

**Comment by jooste** [comment] 2021-12-07 11:52
well, at least your python version is not too old :) I'll try with a config more similar to yours, to see if I can reproduce the error.

**Comment by andersmh** [comment] 2021-12-08 10:23
Well, that's good to hear :) I have tested some different python versions as well. However, I am experiencing other problems with different versions. Is there any version of python and numpy that should be stable to run on the simulator?

**Closed** 2022-03-02 11:42 UTC
